# Generated by Django 3.1.5 on 2021-01-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210107_1009'),
        ('blog', '0005_auto_20210109_1019'),
    ]

    operations = [
    ]
